root = "."
tmp_dir = "tmp"

[build]
cmd = "CGO_ENABLED=0 go build -trimpath -buildvcs=false -o ./tmp/api ./cmd/api"
bin = "tmp/api"
include_ext = ["go"]
exclude_dir = ["vendor","tmp",".git"]

[log]
time = true
