services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: golang:1.22-alpine
    working_dir: /app
    # entry-point - c/ comandos para poder alterar o código
    # e verificar em tempo real (sem precisar reiniciar o container)
    entrypoint: ["/bin/sh", "-c", "/app/dev-entrypoint.sh"]
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=empresasdb
      - RABBIT_URI=amqp://guest:guest@rabbitmq:5672/
      - RABBIT_QUEUE=empresas_log
    ports: ["8080:8080"]
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_data:
